export default {
  TOGGLE_BASIC_INFO: 'TOGGLE_BASIC_INFO',
  TOGGLE_PREFERENCES: 'TOGGLE_PREFERENCES',
  REQUEST_STUDENTS: 'REQUEST_STUDENTS',
  RECEIVE_STUDENTS: 'RECEIVE_STUDENTS',
  ENROLL_STUDENT_SUCCESS: 'ENROLL_STUDENT_SUCCESS',
  ENROLL_STUDENT_FAILURE: 'ENROLL_STUDENT_FAILURE',
  ENROLL_STUDENT_INPROGRESS: 'ENROLL_STUDENT_INPROGRESS'
};
