export default {
  TOGGLE_BASIC_INFO: 'TOGGLE_BASIC_INFO',
  TOGGLE_PREFERENCES: 'TOGGLE_PREFERENCES',
  RECEIVE_STUDENTS: 'RECEIVE_STUDENTS',
  STUDENT_CREATION_SUCCESSFUL: 'STUDENT_CREATION_SUCCESSFUL',
  STUDENT_CREATION_FAILED: 'STUDENT_CREATION_FAILED',
  INPUT_CHANGED: 'INPUT_CHANGED',
};
